//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2_Host_Rest.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serveur/", ConfigurationName="ServiceReference.ServeurDao")]
    public interface ServeurDao {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://serveur/ServeurDao/listerDemandeRequest", ReplyAction="http://serveur/ServeurDao/listerDemandeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Client2_Host_Rest.ServiceReference.listerDemandeResponse listerDemande(Client2_Host_Rest.ServiceReference.listerDemandeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serveur/ServeurDao/listerDemandeRequest", ReplyAction="http://serveur/ServeurDao/listerDemandeResponse")]
        System.Threading.Tasks.Task<Client2_Host_Rest.ServiceReference.listerDemandeResponse> listerDemandeAsync(Client2_Host_Rest.ServiceReference.listerDemandeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://serveur/")]
    public partial class demandeSql : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string hostField;
        
        private string messageField;
        
        private string timeField;
        
        private string userField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
                this.RaisePropertyChanged("host");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listerDemande", WrapperNamespace="http://serveur/", IsWrapped=true)]
    public partial class listerDemandeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serveur/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motCle;
        
        public listerDemandeRequest() {
        }
        
        public listerDemandeRequest(string motCle) {
            this.motCle = motCle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listerDemandeResponse", WrapperNamespace="http://serveur/", IsWrapped=true)]
    public partial class listerDemandeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://serveur/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Client2_Host_Rest.ServiceReference.demandeSql[] @return;
        
        public listerDemandeResponse() {
        }
        
        public listerDemandeResponse(Client2_Host_Rest.ServiceReference.demandeSql[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServeurDaoChannel : Client2_Host_Rest.ServiceReference.ServeurDao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServeurDaoClient : System.ServiceModel.ClientBase<Client2_Host_Rest.ServiceReference.ServeurDao>, Client2_Host_Rest.ServiceReference.ServeurDao {
        
        public ServeurDaoClient() {
        }
        
        public ServeurDaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServeurDaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServeurDaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServeurDaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client2_Host_Rest.ServiceReference.listerDemandeResponse Client2_Host_Rest.ServiceReference.ServeurDao.listerDemande(Client2_Host_Rest.ServiceReference.listerDemandeRequest request) {
            return base.Channel.listerDemande(request);
        }
        
        public Client2_Host_Rest.ServiceReference.demandeSql[] listerDemande(string motCle) {
            Client2_Host_Rest.ServiceReference.listerDemandeRequest inValue = new Client2_Host_Rest.ServiceReference.listerDemandeRequest();
            inValue.motCle = motCle;
            Client2_Host_Rest.ServiceReference.listerDemandeResponse retVal = ((Client2_Host_Rest.ServiceReference.ServeurDao)(this)).listerDemande(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client2_Host_Rest.ServiceReference.listerDemandeResponse> Client2_Host_Rest.ServiceReference.ServeurDao.listerDemandeAsync(Client2_Host_Rest.ServiceReference.listerDemandeRequest request) {
            return base.Channel.listerDemandeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client2_Host_Rest.ServiceReference.listerDemandeResponse> listerDemandeAsync(string motCle) {
            Client2_Host_Rest.ServiceReference.listerDemandeRequest inValue = new Client2_Host_Rest.ServiceReference.listerDemandeRequest();
            inValue.motCle = motCle;
            return ((Client2_Host_Rest.ServiceReference.ServeurDao)(this)).listerDemandeAsync(inValue);
        }
    }
}
